version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    target-branch: main
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
